layout_spectrum: 0.5313287
typography_spectrum: 0.228752
color:
  saturation: 0.7810352
  lightness: 0.740469
  brandStrength: 0.7919678
  rhythmicContrast: 0.6162282
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Djiqui
