collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2759857
  brandStrength: 0
  lightness: 0.9659498
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.1810036
typography_spectrum: 0.4749104
layout_spectrum: 0.9767025
name: Djiqui
